src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $region;



    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Commande", inversedBy="products")
     */
    private $commande;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="product")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sauce", inversedBy="Product_sauce")
     */
    private $sauce;




    public function __construct()
    {

        $this->commande = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public  function getSlug(): string
    {
        return (new Slugify())->slugify($this->nom);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getRegion(): ?int
    {
        return $this->region;
    }

    public function setRegion(int $region): self
    {
        $this->region = $region;

        return $this;
    }
    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormatPrice(): string
    {

        return number_format($this->prix, 0, '', '.');
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * @param mixed $photo
     */
    public function setPhoto($photo): void
    {
        $this->photo = $photo;
    }


    /**
     * @return Collection|Commande[]
     */
    public function getCommande(): Collection
    {
        return $this->commande;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commande->contains($commande)) {
            $this->commande[] = $commande;
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commande->contains($commande)) {
            $this->commande->removeElement($commande);
        }

        return $this;
    }

    public function getProduct(): ?Menu
    {
        return $this->getProduct();
    }

    public function setProduct(?Menu $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getSauce(): ?Sauce
    {
        return $this->sauce;
    }

    public function setSauce(?Sauce $sauce): self
    {
        $this->sauce = $sauce;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }




}

templates/menu/menu.html.twig
{% extends 'base.html.twig' %}


{% block main %}
    {#        start banner noir#}
<div class="banner-menu container-fluid">
    <h5 class="h5-custom menu ">Menu</h5>
</div>
{#        end banner noir#}
<div class="nav nav-pills justify-content-center ftco-animate" id="v-pills-tab" role="tablist"
     aria-orientation="vertical">
    <a class="nav-link py-3 px-4 active" id="menus" data-toggle="pill" href="#menus" role="tab"
       aria-controls="v-pills-profile" aria-selected="false"><span class="flaticon-cutlery"></span>Menu</a>
    <a class="nav-link py-3 px-4" id="sandwich" data-toggle="pill" href="#sandwich" role="tab"
       aria-controls="v-pills-messages" aria-selected="false"><span class="flaticon-cheers"></span>Sandwich</a>
    <a class="nav-link py-3 px-4" id="frite" data-toggle="pill" href="#frite" role="tab"
       aria-controls="v-pills-messages" aria-selected="false"><span class="flaticon-cheers"></span>Frite</a>
    <a class="nav-link py-3 px-4" id="boisson" data-toggle="pill" href="#boisson" role="tab"
       aria-controls="v-pills-messages" aria-selected="false"><span class="flaticon-cheers"></span>Boisson</a>
    <a class="nav-link py-3 px-4  " id="dessert" data-toggle="pill" href="#dessert" role="tab"
       aria-controls="v-pills-home" aria-selected="true"><span class="menu"></span>Dessert</a>
</div>
{#    start menu-------------------------------------------------------------------------------------------------------------- bzh#}
<section class="section-banner">
    <div class="container  menus">
        <div class="row row-menu">
            {% for menu in menu %}
                <div class="card card-custom text-center col-lg-6 col-md-12" style="width: 18rem;">
                    <p class="typeAndPrice"> Prix:<br><em>{{ menu.prix }} €</em></p>
                    <p class="img-region">
                        {% if menu.region == 1 %}
                            <img src="img/logobzh.png" alt="lion">
                        {% elseif menu.region == 2 %}
                            <img src="img/logolion.png" alt="lion">
                        {% endif %}
                    </p>
                    <img src="{{ asset("uploads/" ~ menu.image) }}" class="card-img-top image-menu" alt="...">
                    <div class="card-body">
                        <h4 class="card-title text-align">{{ menu.nom }} </h4>
                        {{ menu.description }}<br>
                        <a class="btn btn-primary" role="button"  href="{{ path('menu.show', {id: menu.id , slug: menu.slug}) }}">Détails & quantité</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {#    end menu bzh#}
    {#    start sandwich -------------------------------------------------------------------------------------------------------------- ch'ti#}
    <section class="section-banner">
        <div class="container sandwich">
            <div class="row row-menu">
                {% for sandwich in sandwich %}
                    <div class="card card-custom text-center col-lg-6 col-md-12" style="width: 18rem;">
                        <p class="typeAndPrice"> Prix:<br><em>{{ sandwich.prix }} €</em></p>
                        <p class="img-region">
                            {% if sandwich.region == 1 %}
                                <img src="img/logobzh.png" alt="lion">
                            {% elseif sandwich.region == 2 %}
                                <img src="img/logolion.png" alt="lion">
                            {% endif %}
                        </p>
                        <img src="{{ asset("uploads/" ~ sandwich.image) }}" class="card-img-top image-menu"
                             alt="...">
                        <div class="card-body">
                            <h4 class="card-title text-align">{{ sandwich.nom }}</h4>
                            {{ sandwich.description }}<br>
                            <a class="btn btn-primary" role="button"
                               href="{{ path('menu.show', {id: sandwich.id , slug: sandwich.slug}) }}">Details...</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {#    end sandwich #}
    {#    start sandwich -------------------------------------------------------------------------------------------------------------- ch'ti#}
    <section class="section-banner">
        <div class="container frite">
            <div class="row row-menu">
                {% for frite in frite %}
                    <div class="card card-custom text-center col-lg-6 col-md-12" style="width: 18rem;">
                        <p class="typeAndPrice"> Prix:<br><em>{{ frite.prix }} €</em></p>
                        <p class="img-region">
                            {% if frite.region == 1 %}
                                <img src="img/logobzh.png" alt="lion">
                            {% elseif frite.region == 2 %}
                                <img src="img/logolion.png" alt="lion">
                            {% endif %}
                        </p>
                        <img src="{{ asset("uploads/" ~ frite.image) }}" class="card-img-top image-menu"
                             alt="...">
                        <div class="card-body">
                            <h4 class="card-title text-align">{{ frite.nom }}</h4>
                            {{ frite.description }}<br>
                            <a class="btn btn-primary" role="button"
                               href="{{ path('menu.show', {id: frite.id , slug: frite.slug}) }}">Details...</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {#    end sandwich #}
    {#    start boisson -------------------------------------------------------------------------------------------------------------- ch'ti#}
    <section class="section-banner">
        <div class="container boisson">
            <div class="row row-menu">
                {% for boisson in boisson %}
                    <div class="card card-custom text-center col-lg-3 col-md-12" style="width: 18rem;">
                        <p class="typeAndPrice"> Prix:<br><em>{{ boisson.prix }} €</em></p>

                        <img src="{{ asset("uploads/" ~ boisson.image) }}" class="card-img-top image-menu" alt="...">
                        <div class="card-body">
                            <h4 class="card-title text-align">{{ boisson.nom }}</h4>
                            <a class="btn btn-primary" role="button"
                               href="{{ path('menu.show', {id: boisson.id , slug: boisson.slug}) }}">Details...</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {#    end boisson bzh#}
    {#    start dessert -------------------------------------------------------------------------------------------------------------- ch'ti#}
    <section class="section-banner">
        <div class="container dessert">
            <div class="row row-menu">
                {% for dessert in dessert %}
                    <div class="card card-custom text-center col-lg-3 col-md-12" style="width: 18rem;">
                        <p class="typeAndPrice"> Prix:<br><em>{{ dessert.prix }} €</em></p>
                        <p class="img-region">
                            {% if dessert.region == 1 %}
                                <img src="img/logobzh.png" alt="lion">
                            {% elseif dessert.region == 2 %}
                                <img src="img/logolion.png" alt="lion">
                            {% endif %}
                        </p>
                        <img src="{{ asset("uploads/" ~ dessert.image) }}" class="card-img-top image-menu" alt="...">
                        <div class="card-body">
                            <h4 class="card-title text-align">{{ dessert.nom }}</h4>
                            {{ dessert.description }}<br>
                            <a class="btn btn-primary" role="button"
                               href="{{ path('menu.show', {id: dessert.id , slug: dessert.slug}) }}">Details...</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <script>

        $(document).ready(function () {

            $('.sandwich').hide();
            $('.frite').hide();
            $('.boisson').hide();
            $('.dessert').hide();
            $('.menus').show();

            $("#menus").click(function () {
                $('.sandwich').hide();
                $('.frite').hide();
                $('.boisson').hide();
                $('.dessert').hide();
                $('.menus').show();
            });
            $("#sandwich").click(function () {
                $('.menus').hide();
                $('.frite').hide();
                $('.boisson').hide();
                $('.dessert').hide();
                $('.sandwich').show();
            });
            $("#frite").click(function () {
                $('.menus').hide();
                $('.sandwich').hide();
                $('.boisson').hide();
                $('.dessert').hide();
                $('.frite').show();
            });
            $("#dessert").click(function () {
                $('.menus').hide();
                $('.sandwich').hide();
                $('.frite').hide();
                $('.boisson').hide();
                $('.dessert').show();
            });
            $("#boisson").click(function () {
                $('.menus').hide();
                $('.sandwich').hide();
                $('.frite').hide();
                $('.dessert').hide();
                $('.boisson').show();
            });
        });
    </script>
    {% endblock %}

templates/menu/produit.html.twig
<div class="card card-custom text-center col-lg-6 col-md-12" style="width: 18rem;">
    <p class="typeAndPrice"> Prix:<br><em>{{ article.prix }} €</em></p>
    <img src="{{ asset("uploads/" ~ article.photo) }}" class="card-img-top image-menu" alt="...">
    <div class="card-body">
        <h4 class="card-title text-align">{{ article.nom }} </h4>
    <h6> {{ article.description }}</h6>

        <a class="btn btn-primary" role="button"  href="{{ path('menu.show', {id: article.id , slug: article.slug}) }}">Détails & quantité</a>
    </div>
</div>





{#<div class="col-3">#}
{#    <div class="car text-center" >#}
{#        <div style="border-style: groove;background-color: white" >#}
{#            <img  class="image-style" src="{{ asset("images/") ~ product.nom }}.jpg" height="200" alt="{{ product.nom }}" />#}
{#            <div class="card-body" style="background-color: #F5F5F5">#}
{#                <h5 class="card-title">#}
{#                    <a id="produits" href="#">{{ product.nom }}</a>#}
{#                </h5>#}
{#                <p class="card-text">#}
{#                    {{ product.description}}#}
{#                </p>#}
{#                <div class="text-danger" style="font-size: 2em">{{ product.getFormatPrice }} €</div>#}
{#                <p class="card-text">#}
{#                    <a class="btn btn-primary" role="button"  href="{{ path('menu.show', {id: product.id , slug: product.slug}) }}">Details...</a>#}
{#                </p>#}
{#            </div>#}
{#        </div>#}
{#    </div></br>#}
{#</div>#}

templates/menu/show.html.twig
{% extends 'base.html.twig' %}

{% block title product.nom %}

{% block main %}
    <div class="banner-menu container-fluid">
        <h5 class="h5-custom menu ">Détail</h5>
    </div>


    <section class="section-banner">
        <div class="container row-login menus">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row  no-gutters">
                    <div class="col-md-4">
                        <img class="card-img-top image-menu" src="{{ asset("uploads/" ~ menu.image) }}" height="200"
                             alt="{{ menu.nom }}"/>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ menu.nom }}</h5>
                            <p class="card-text">{{ menu.description  | nl2br }}</p>
                            <p class="card-text">
                                <small class="text-muted">{{ menu.formatPrice }} €</small>
                            </p>
                            <form action="{{ path('panier.ajout', {'id': menu.id} ) }}" method="get">
                                Quantité <input type="number" style="width: 30%" max="99" min="1" name="qte" value="1"/>
                                </p>
                                <p class="card-text">
                                    <select class="custom-select fadeIn second" name="name">
                                        {% for sauce in sauce %}
                                            <option value="{{ sauce.nom }}">{{ sauce.nom }}</option>
                                        {% endfor %}
                                    </select>
                                </p>
                                <p class="card-text">
                                    <button class="btn btn-success btn-lg">Au panier!</button>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}